--liquibase formatted sql
--changeset <mysql>:<add-products>

INSERT INTO products (name, price, rating, description, product_image) VALUES ('Ноутбук Lenovo IdeaPad 3 15ALC6', 24899, 3.9, '\"Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / AMD Radeon Graphics / без ОД / Wi-Fi / Bluetooth / веб-камера / без ОС / 1.65 кг / сірий\"', 'https://content.rozetka.com.ua/goods/images/big/280562850.jpg'),
                                                                              ('Ноутбук Acer Aspire 7 A715-42G-R3EZ', 30999, 4, '\"Екран 15.6\" IPS (1920x1080) Full HD, матовий / AMD Ryzen 5 5500U (2.1 - 4.0 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce GTX 1650, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.15 кг / чорний\"', 'https://content2.rozetka.com.ua/goods/images/big/175333156.jpg'),
                                                                              ('Мобільний телефон Apple iPhone 11 128GB White', 25499, 4.8, '\"Екран (6.1\", IPS (Liquid Retina HD), 1792x828) / Apple A13 Bionic / основна подвійна камера: 12 Мп + 12 Мп, фронтальна камера: 12 Мп / RAM 4 ГБ / 128 ГБ вбудованої пам''яті / 3G / LTE / GPS / ГЛОНАСС / Nano-SIM / iOS 13 / 3046 мА·год\"', 'https://content2.rozetka.com.ua/goods/images/big/310649564.jpg'),
                                                                              ('Мобільний телефон Samsung Galaxy S23 Ultra', 57999, 4.8, '\"Экран (6.8\", Dynamic AMOLED 2X, 3088x1440) / Qualcomm Snapdragon 8 Gen 2 for Galaxy (3.36 ГГц + 2.8 ГГц + 2.8 ГГц + 2.0 ГГц) / основная квадро-камера: 200 Мп + 12 Мп + 10 Мп + 10 Мп, фронтальная 12 Мп / RAM 12 ГБ / 256 ГБ встроенной памяти / 3G / LTE / 5G / GPS / поддержка 2х SIM-карт (Nano-SIM) / Android 13 / 5000 мА*ч\"', 'https://content2.rozetka.com.ua/goods/images/big/310649564.jpg'),
                                                                              ('Холодильник SAMSUNG RB38T600FWW/UA', 23599, 3.7, '"Загальний об''єм холодильника 390 л. Тип холодильника Двокамерний. Клас енергоспоживання A+. Система розморожування холодильної камери No Frost (суха). Габарити (ВхШхГ)203 x 59.5 x 65.8 см"', 'https://content2.rozetka.com.ua/goods/images/big/249197939.jpg'),
                                                                              ('Холодильник Whirlpool', 19355, 3.2, 'Загальний об''єм холодильника 378 л. Тип холодильника Двокамерний. Клас енергоспоживання A+. Система розморожування холодильної камери No Frost (суха). Габарити (ВхШхГ) 191.2 х 59.6 х 67.8 см', 'https://content.rozetka.com.ua/goods/images/big/278194226.jpg'),
                                                                              ('Пральна машина вузька WHIRLPOOL WRBSB 6228 B UA', 13999, 4.3, 'Максимальне завантаження білизни 6 кг. Тип двигуна Інверторний. Клас енергоспоживання А+++. Кількість програм 16. Технічні особливості З дисплеєм. Максимальна швидкість віджимання, об/хв 1200. Габарити (ВхШхГ) 85 х 59.5 х 42.5 см', 'https://content.rozetka.com.ua/goods/images/big/286602037.jpg'),
                                                                              ('Смарт Годівниця для собак і кішок Petkit Smart Fresh Element 3 (5L)', 1200, 3.0, 'Завдяки вбудованому Wi-Fi й зручному застосунку Petkit, годування чотириногого друга перетворюється на простий і регулярний процес, який не вимагає від вас особливих зусиль або особистої присутності. Просто встановіть час приймання їжі та розміри порції, а про все інше подбає Petkit Smart Fresh Element 3. Отже, розумна автоматична годівниця допоможе вам піклуватися про свою кішку або собаку, хай де б ви перебували.', 'https://content2.rozetka.com.ua/goods/images/big/186302274.jpg'),
                                                                              ('Capybara', 12999, 5.0, 'Капиба́ра[1], или водосви́нка[2] (лат. Hydrochoerus hydrochaeris) — полуводное травоядное млекопитающее из подсемейства водосвинковых (Hydrochoerinae), один из двух (наряду с малой водосвинкой) ныне существующих видов рода водосвинки. Капибара — самый крупный среди современных грызунов.', 'https://faunistics.com/wp-content/uploads/2021/06/1.jpg'),
                                                                              ('Комп''ютерний стіл Cougar MARS Black', 17999, 4.6, 'Для повного занурення в ігрову атмосферу ігровий стіл MARS оснащений двостороннім RGB підсвічуванням з можливістю індивідуального налаштування. Також можлива синхронізація RGB підсвічування з найбільш популярними стандартами материнських плат, такими як Asus Aura Sync, Gigabyte RGB Fusion, MSI Mystic Light Sync і ASRock Polychrome Sync шляхом підключення по 5В шині.', 'https://content2.rozetka.com.ua/goods/images/big/19672244.jpg'),
                                                                              ('Шафа Doros Гелар 4Д 155 х 49.5 х 203.4 см Біла', 8247, 3.1, 'Корпус і фасад виробу виготовлений із ламінованого ДСП завтовшки 16 мм. Крайка зовнішніх деталей — 2 мм, полиці, а також ящики — 0,5 мм. Шафи спроєктовано в такий спосіб, щоб забезпечити міцну, безпечну та стійку конструкцію. Фурнітуру перевіряють на міцність і довговічність. Зберігайте паковання до повного складання виробу, оскільки його наявність є обов''язковою умовою для прийняття рекламацій щодо товару.', 'https://content.rozetka.com.ua/goods/images/big/160389223.jpg'),
                                                                              ('Планшет Apple iPad 10.2" 2021 Wi-Fi 64 GB Silver', 16999, 4.6, 'Екран 10.2" IPS (2160x1620) MultiTouch / Apple A13 Bionic (2.65 ГГц) / 64 ГБ вбудованої пам''яті / Wi-Fi / Bluetooth 4.2 / основна камера 8 Мп, фронтальна — 12 Мп / iPadOS 15 / 487 г / сріблястий', 'https://content.rozetka.com.ua/goods/images/big/224010066.jpg'),
                                                                              ('Планшет Lenovo Tab M10 HD (2nd Gen) LTE 3/32GB Iron Grey', 6999, 4.5, 'Экран 10.1" (1280x800) MultiTouch / MediaTek Helio P22T (2.3 ГГц) / RAM 3 ГБ / 32 ГБ встроенной памяти + microSD / LTE / Wi-Fi / Bluetooth 5.0 / основная камера 8 Мп, фронтальная - 5 Мп / GPS / ГЛОНАСС / Android 10 / 420 г / серый', 'https://content1.rozetka.com.ua/goods/images/big/292024267.png'),
                                                                              ('Ноутбук ASUS TUF Gaming F15 FX506HC-HN006', 38999, 4.8, 'Екран 15.6" IPS (1920x1080) Full HD 144 Гц, матовий / Intel Core i5-11400H (2.7 - 4.5 ГГц) / RAM 16 ГБ / SSD 512 ГБ / nVidia GeForce RTX 3050, 4 ГБ / без ОД / LAN / Wi-Fi / Bluetooth / веб-камера / без ОС / 2.3 кг / сірий', 'https://content2.rozetka.com.ua/goods/images/big/278076445.jpg');
INSERT INTO products_categories (product_id, category_id) VALUES (1,1),
                                                                 (2,1),
                                                                 (3,2),
                                                                 (4,2),
                                                                 (5,3),
                                                                 (6,3),
                                                                 (7,3),
                                                                 (8,4),
                                                                 (9,5),
                                                                 (10,6),
                                                                 (11,6),
                                                                 (12,7),
                                                                 (13,7),
                                                                 (14,1);



--rollback DELETE FROM products;